---
title: "Sandbox"
output: html_notebook
---

```{r}
abilities <- c(
  "strength",
  "dexterity",
  "constitution",
  "intelligence",
  "wisdom",
  "charisma"
)

races <- c(  
  "dragonborn",
  "dwarf",
  "elf",
  "gnome",
  "half.elf",
  "half.orc",
  "halfling",
  "human",
  "tiefling"
)

roll <- function(n, d) {
  values <- sample(1:d, n, replace = TRUE) # roll a d-sided die n times
  sum <- sum(values)
  result <- list(values, sum)
  names(result) <- c("values", "sum")
  return(result)
}

roll.stat <- function() {
  result <- roll(4, 6) # roll 4d6
  lowest <- min(result$values) # take the lowest 
  return(result$sum - lowest) # and remove it from the sum 
}

roll.stats <- function(n) {
  X <- matrix(1:n*6, nrow = n, ncol = 6)
  X[] <- sapply(X, function(ij) roll.stat())
  df <- as.data.frame(X)
  names(df) <- sapply(abilities, function(a) sprintf("%s.roll", a), USE.NAMES = FALSE)
  df$race <- apply(df, 1, function(i) sample(races, 1))
  return(df)
}

sample(races, 1)
```

```{r}
set.seed(0)
stats.rolled <- roll.stats(100)
```

```{r}
speed <- c(30, 25, 30, 25, 30, 30, 25, 30, 30)
strength.mod <- c(2, 0, 0, 0, 0, 2, 0, 1, 0)
dexterity.mod <- c(2, 0, 0, 0, 0, 2, 0, 1, 0)
constitution.mod <- c(0, 2, 0, 0, 0, 1, 0, 1, 0)
wisdom.mod <- c(0, 0, 0, 0, 0, 0, 0, 1, 0)
intelligence.mod <- c(0, 0, 0, 2, 0, 0, 0, 1, 1)
charisma.mod <- c(1, 0, 0, 0, 2, 0, 0, 1, 2)

racial.mods <- data.frame(
  speed,
  strength.mod,
  dexterity.mod,
  constitution.mod,
  wisdom.mod,
  intelligence.mod,
  charisma.mod
)

rownames(racial.mods) <- races
racial.mods
```

```{r}
stats <- merge(x = stats.rolled, y = racial.mods, by.x = "race", by.y = "row.names", all = TRUE)
stats
```

```{r}
# half elves get +2 charisma and +1 to any two abilities of their choice
set.seed(NULL)
mod.options <- abilities[abilities != "charisma"]
mod.options <- sapply(mod.options, function(a) sprintf("%s.mod", a), USE.NAMES = FALSE)
for (i in 1:nrow(stats)) {
  if (stats[i, "race"] == "half.elf") {
    chosen.mods <- sample(mod.options, 2, replace = FALSE)
    stats[i, chosen.mods[1]] = 1
    stats[i, chosen.mods[2]] = 1
  }
}
```

```{r}
stats$strength <- stats$strength.roll + stats$strength.mod
stats$dexterity <- stats$dexterity.roll + stats$dexterity.mod 
stats$constitution <- stats$constitution.roll + stats$constitution.mod
stats$wisdom <- stats$wisdom.roll + stats$wisdom.mod
stats$intelligence <- stats$intelligence.roll + stats$intelligence.mod
stats$charisma <- stats$charisma.roll + stats$charisma.mod
```




















